trigger:
- '*'
pr:
- '*'

strategy:
  matrix:
    mac:
      imageName: 'macOS-latest'
    windows:
      imageName: 'windows-latest'

pool:
  vmImage: $(imageName)

variables:
  pnpm_config_cache: $(Pipeline.Workspace)/.pnpm-store

steps:
- task: Cache@2
  inputs:
    key: 'pnpm | "$(Agent.OS)" | pnpm-lock.yaml'
    path: $(pnpm_config_cache)
  displayName: Cache pnpm

- script: |
    corepack enable
    corepack prepare pnpm@latest-9 --activate
    pnpm config set store-dir $(pnpm_config_cache)
  displayName: "Setup pnpm"

- script: |
    pnpm install
  displayName: "pnpm install"

- script: |
    pnpm test
  displayName: "pnpm test"
