name: Run VSCode Extension Tests

on:
  schedule:
    - cron: "0 7 * * *" # 15:00 PM in China
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        node-version: ["20.17.0"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup binary path for windows
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          "C:\Users\runneradmin\.moon\bin" | Out-File -FilePath $env:GITHUB_PATH -Append

      - name: Setup binary path for macOS
        if: ${{ matrix.os == 'macos-latest' }}
        run: |
          mkdir -p "$HOME/.moon/bin"
          echo "$HOME/.moon/bin" >> $GITHUB_PATH

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup Pnpm package manager
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install dependencies
        run: pnpm install

      - name: Run tests
        run: |
          export XDG_RUNTIME_DIR=/run/user/$(id -u)
          export DBUS_SESSION_BUS_ADDRESS=unix:path=$XDG_RUNTIME_DIR/bus
          dbus-daemon --session --address=$DBUS_SESSION_BUS_ADDRESS --nofork --nopidfile --syslog-only &
          mkdir ~/.vscode && echo '{ "disable-hardware-acceleration": true }' > ~/.vscode/argv.json
          xvfb-run -a pnpm test
        if: runner.os == 'Linux'

      - name: Run tests
        run: pnpm test
        if: runner.os != 'Linux'
